version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    image: abacystaa/server:latest
    container_name: server_c
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

  client:
    image: abacystaa/client:latest
    container_name: client_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  mongo-data:
